FROM python:3.7
WORKDIR /flask-s3-upload

COPY requirements.txt ./
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY . .

ENV S3_BUCKET=<your s3 bucket name>
ENV S3_KEY=<your s3 iam user key>
ENV S3_SECRET_ACCESS_KEY=<your s3 iam user secret access key>

EXPOSE 5000

CMD ["gunicorn", "app:app", "-c", "./gunicorn.conf.py"]